# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(567, 167)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.origin_label = QtWidgets.QLabel(self.centralwidget)
        self.origin_label.setGeometry(QtCore.QRect(100, 20, 64, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.origin_label.setFont(font)
        self.origin_label.setObjectName("origin_label")
        self.dest_label = QtWidgets.QLabel(self.centralwidget)
        self.dest_label.setGeometry(QtCore.QRect(365, 20, 95, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dest_label.setFont(font)
        self.dest_label.setObjectName("dest_label")
        self.origin = QtWidgets.QLineEdit(self.centralwidget)
        self.origin.setGeometry(QtCore.QRect(50, 50, 184, 31))
        self.origin.setObjectName("origin")
        self.dest = QtWidgets.QLineEdit(self.centralwidget)
        self.dest.setGeometry(QtCore.QRect(310, 50, 211, 31))
        self.dest.setObjectName("dest")
        self.switch_2 = QtWidgets.QPushButton(self.centralwidget)
        self.switch_2.setGeometry(QtCore.QRect(233, 20, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(True)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.switch_2.setFont(font)
        self.switch_2.setObjectName("switch_2")
        self.translate = QtWidgets.QPushButton(self.centralwidget)
        self.translate.setGeometry(QtCore.QRect(200, 100, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.translate.setFont(font)
        self.translate.setObjectName("translate")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.origin_label.setText(_translate("MainWindow", "РУССКИЙ"))
        self.dest_label.setText(_translate("MainWindow", "АНГЛИЙСКИЙ"))
        self.switch_2.setText(_translate("MainWindow", "<------>"))
        self.translate.setText(_translate("MainWindow", "Перевести"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
